package com.name.cn.mydiary.data.source.local;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.name.cn.mydiary.data.bookdetail.Journal;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "JOURNAL".
*/
public class JournalDao extends AbstractDao<Journal, Long> {

    public static final String TABLENAME = "JOURNAL";

    /**
     * Properties of entity Journal.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property JournalOwnId = new Property(1, Long.class, "journalOwnId", false, "JOURNAL_OWN_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
    }

    private Query<Journal> diary_JournalListQuery;

    public JournalDao(DaoConfig config) {
        super(config);
    }
    
    public JournalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"JOURNAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"JOURNAL_OWN_ID\" INTEGER NOT NULL ," + // 1: journalOwnId
                "\"NAME\" TEXT NOT NULL );"); // 2: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"JOURNAL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Journal entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getJournalOwnId());
        stmt.bindString(3, entity.getName());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Journal entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getJournalOwnId());
        stmt.bindString(3, entity.getName());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Journal readEntity(Cursor cursor, int offset) {
        Journal entity = new Journal( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // journalOwnId
            cursor.getString(offset + 2) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Journal entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setJournalOwnId(cursor.getLong(offset + 1));
        entity.setName(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Journal entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Journal entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Journal entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "journalList" to-many relationship of Diary. */
    public List<Journal> _queryDiary_JournalList(Long journalOwnId) {
        synchronized (this) {
            if (diary_JournalListQuery == null) {
                QueryBuilder<Journal> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.JournalOwnId.eq(null));
                diary_JournalListQuery = queryBuilder.build();
            }
        }
        Query<Journal> query = diary_JournalListQuery.forCurrentThread();
        query.setParameter(0, journalOwnId);
        return query.list();
    }

}
